import test from 'node:test';
import assert from 'node:assert/strict';
import {collection,filmById,recommendCollection,searchCollection} from '../lib/catalogue';
import {weights,commitSnapshot,restoreSnapshot,parseSession,EMPTY_SESSION,SnapshotSchema,type Snapshot} from '../lib/domain';
import {allowedSourceUrl,supports} from '../lib/server/grounding';
const film=(id:string)=>filmById(id)!;
const snapshot=(id:string,trail:string[]=[]):Snapshot=>SnapshotSchema.parse({id,createdAt:new Date().toISOString(),seeds:[film('closeup')],trail:trail.map(film),...recommendCollection([film('closeup')],trail.map(film))});
test('Korean titles, director and punctuation search resolve real films',()=>{assert.equal(searchCollection('클로즈업')[0].id,'closeup');assert.ok(searchCollection('Kiarostami').length>1);assert.equal(searchCollection('F for Fake')[0].id,'fake');assert.equal(searchCollection('no matching movie').length,0);});
test('latest follow leads while every prior film retains positive influence',()=>{const w=weights([film('closeup'),film('fake')],[film('apple'),film('boards')]);assert.ok(Math.abs(w.reduce((s,x)=>s+x.weight,0)-1)<1e-12);assert.ok(w.every(x=>x.weight>0));assert.ok(w[3].weight>w[2].weight&&w[2].weight>w[0].weight);assert.equal(w[0].weight,w[1].weight);});
test('every starting point has grounded, unique, non-self recommendations',()=>{for(const seed of collection){const batch=recommendCollection([seed],[]);assert.ok(batch.recommendations.length>=3);assert.ok(batch.recommendations.length<=12);const sources=new Set(batch.sources.map(s=>s.id));assert.equal(new Set(batch.recommendations.map(r=>r.film.id)).size,batch.recommendations.length);for(const r of batch.recommendations){assert.notEqual(r.film.id,seed.id);assert.ok(r.sourceIds.every(id=>sources.has(id)));assert.ok(r.connections.every(c=>c.anchorId===seed.id&&c.sourceIds.every(id=>sources.has(id))));}}});
test('follow excludes all selected films and changes the rank',()=>{const a=recommendCollection([film('closeup')],[]);const b=recommendCollection([film('closeup')],[film('apple')]);assert.ok(b.recommendations.every(r=>!['closeup','apple'].includes(r.film.id)));assert.notDeepEqual(a.recommendations.map(r=>r.film.id),b.recommendations.map(r=>r.film.id));});
test('undo restores the exact batch and evidence; successful branch replaces suffix only',()=>{let s=commitSnapshot(EMPTY_SESSION,snapshot('zero'),true);s=commitSnapshot(s,snapshot('one',['apple']),false);s=commitSnapshot(s,snapshot('two',['apple','boards']),false);const original=s.snapshots[0];s=restoreSnapshot(s,0);assert.equal(s.snapshots[s.cursor],original);assert.equal(s.snapshots.length,3);assert.throws(()=>commitSnapshot(s,{...snapshot('bad'),recommendations:[]},false));assert.equal(s.snapshots.length,3);s=commitSnapshot(s,snapshot('branch',['fake']),false);assert.deepEqual(s.snapshots.map(x=>x.id),['zero','branch']);assert.deepEqual(parseSession(JSON.stringify(s)),JSON.parse(JSON.stringify(s)));});
test('invalid saved evidence and unknown restore targets are rejected',()=>{const s=commitSnapshot(EMPTY_SESSION,snapshot('initial'),true);s.snapshots[0].recommendations[0].connections[0].sourceIds=['missing'];assert.throws(()=>parseSession(JSON.stringify(s)));assert.throws(()=>restoreSnapshot(s,-1));});
test('exhausted collection returns an honest empty batch',()=>{const b=recommendCollection([collection[0]],collection.slice(1));assert.deepEqual(b.recommendations,[]);});
test('source fetches reject private, lookalike, credential-bearing and non-essay URLs',()=>{assert.ok(allowedSourceUrl('https://www.criterion.com/current/posts/123-a-film'));for(const u of ['http://www.criterion.com/current/posts/x','https://localhost/a','https://www.criterion.com.evil.test/current/posts/x','https://x@www.criterion.com/current/posts/x','https://www.criterion.com/films/123'])assert.equal(allowedSourceUrl(u),false);});
test('supporting span must exist and name its supported films itself',()=>{const span='Close-Up and The Apple use reenactment to reconsider who can represent a life.';assert.ok(supports(span,span,['Close-Up','The Apple']));assert.equal(supports('Close-Up / The Apple. A generic comment about cinema without any named film.','A generic comment about cinema without any named film.',['Close-Up','The Apple']),false);assert.equal(supports(span,'An invented comparison of Close-Up and The Apple.',['Close-Up']),false);});

test('Korean display uses database labels and preserves a title when none exists',async()=>{const {titleOf}=await import('../lib/domain');assert.equal(titleOf(film('closeup'),'ko'),'클로즈업');assert.equal(titleOf({...film('closeup'),titleKo:undefined},'ko'),'Close-Up');});
test('overlap bonus is modest and duplicate or unknown anchors earn no extra weight',async()=>{const {connectionScore}=await import('../lib/ranking');const template=recommendCollection([film('closeup')],[]).recommendations[0];const edge=template.connections[0];const one={...template,connections:[edge]};const duplicates={...template,connections:[edge,edge,{...edge,anchorId:'unknown'}]};assert.equal(connectionScore(one,[film('closeup')],[]),connectionScore(duplicates,[film('closeup')],[]));const two={...template,connections:[{...edge,anchorId:'closeup',relation:'direct_connection' as const},{...edge,anchorId:'fake',relation:'direct_connection' as const}]};assert.equal(connectionScore(two,[film('closeup'),film('fake')],[]),1.06);});
test('diversity changes the order of equally supported candidates without losing evidence',async()=>{const {rankRecommendations}=await import('../lib/ranking');const template=recommendCollection([film('closeup')],[]).recommendations[0];const a={...template,film:{...template.film,id:'a',director:'Director A',country:'Iran',year:1990}};const b={...template,film:{...template.film,id:'b',director:'Director A',country:'Iran',year:1991}};const c={...template,film:{...template.film,id:'c',director:'Director C',country:'Japan',year:1960}};const ranked=rankRecommendations([a,b,c],[film('closeup')],[]);assert.deepEqual(ranked.map(r=>r.film.id),['a','c','b']);assert.equal(ranked[0].sourceIds,template.sourceIds);});

import {titleMatches,titleMentioned} from '../lib/server/grounding';
test('evidence titles preserve boundaries, short names and documented article variants',()=>{
 assert.equal(titleMentioned('A honeymoon sequence','Moon'),false);
 assert.equal(titleMentioned('The critic compares Moon and Solaris.','Moon'),true);
 assert.equal(titleMentioned('A study of M and its sound design.','M'),true);
 assert.equal(titleMentioned('The road movie tradition','The Road'),true);
 assert.equal(titleMentioned('a broad palette','The Road'),false);
 assert.equal(titleMentioned('Close-Up and Moment of Innocence explore reenactment.','A Moment of Innocence'),true);
 assert.equal(titleMatches('The Moment of Innocence','A Moment of Innocence'),true);
});
