"use client";
import {useEffect,useRef,useState,useCallback} from 'react';
import {ArrowRight,ArrowUpRight,X,Undo2,History,Check,LoaderCircle,BookOpen,ChevronRight} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Popover,PopoverTrigger,PopoverContent} from '@/components/ui/popover';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {FilmSearch} from '@/components/film-search';
import {FilmPoster} from '@/components/film-poster';
import {collection} from '@/lib/catalogue';
import {EMPTY_SESSION,STORAGE_KEY,SnapshotSchema,commitSnapshot,restoreSnapshot,parseSession,type Session,type Film,type Snapshot,type Recommendation,type Connection,type Source} from '@/lib/domain';

type Pending={id:string,kind:'initial'|'follow',film?:Film,controller:AbortController};
type ApiBatch={error?:{message?:string},requestId:string,baseSnapshotId:string|null,generatedAt:string,seeds:Film[],trail:Film[],recommendations:Recommendation[],sources:Source[],mode:'collection'|'live'};
type Nav={closeup:true,view:'entry'|'results',filmId?:string};
const relationLabel:Record<Connection['relation'],string>={direct_connection:'A critical connection',curatorial_association:'A curatorial connection',grounded_interpretation:'A CLOSEUP reading'};
const sourceLabel:Record<Source['type'],string>={academic:'Academic',criticism:'Criticism',festival:'Programme',catalogue:'Curation'};
function Brand({small=false,onClick}:{small?:boolean,onClick?:()=>void}){return onClick?<button className={`brand ${small?'small':''}`} onClick={onClick} aria-label="Back to starting films">CLOSEUP<img src="/mark.svg" alt=""/></button>:<div className={`brand ${small?'small':''}`}>CLOSEUP<img src="/mark.svg" alt=""/></div>}
function safeLink(url:string){try{return new URL(url).protocol==='https:'?url:'#'}catch{return '#'}}
function readableDate(value:string|null){if(!value)return '';return value.slice(0,4);}

export default function Home(){
 const [session,setSession]=useState<Session>(EMPTY_SESSION);const current=useRef<Session>(EMPTY_SESSION);
 const [ready,setReady]=useState(false);const [view,setView]=useState<'entry'|'results'>('entry');const [drawerId,setDrawerId]=useState<string|null>(null);
 const [pending,setPending]=useState<Pending|null>(null);const pendingRef=useRef<Pending|null>(null);const [error,setError]=useState('');const [credits,setCredits]=useState(false);const [historyOpen,setHistoryOpen]=useState(false);
 const [mode,setMode]=useState<'collection'|'live'>('collection');const [storageWarning,setStorageWarning]=useState(false);const heading=useRef<HTMLHeadingElement>(null);const lastPoster=useRef<HTMLElement|null>(null);const scrollBySnapshot=useRef<Record<string,number>>({});
 const active=session.snapshots[session.cursor];const detail=active?.recommendations.find(r=>r.film.id===drawerId);
 const update=useCallback((s:Session)=>{current.current=s;setSession(s);},[]);
 const cancel=useCallback(()=>{pendingRef.current?.controller.abort();pendingRef.current=null;setPending(null);setError('');},[]);
 useEffect(()=>{
  let saved=EMPTY_SESSION;try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)saved=parseSession(raw);}catch{toast('Your saved trail could not be restored. Start a new one.');}
  update(saved);const restored=saved.cursor>=0;history.replaceState({closeup:true,view:'entry'} satisfies Nav,'',location.pathname);if(restored){history.pushState({closeup:true,view:'results'} satisfies Nav,'','#trail');setView('results');}
  setReady(true);const controller=new AbortController();fetch('/api/status',{signal:controller.signal}).then(r=>r.ok?r.json():null).then(s=>{const status=s as {mode?:string}|null;if(status?.mode==='live'||status?.mode==='collection')setMode(status.mode)}).catch(()=>{});
  function onPop(e:PopStateEvent){cancel();setCredits(false);setHistoryOpen(false);setError('');const nav=e.state as Nav|null;if(!nav?.closeup||nav.view==='entry'){setView('entry');setDrawerId(null);return;}setView('results');const sn=current.current.snapshots[current.current.cursor];setDrawerId(nav.filmId&&sn?.recommendations.some(r=>r.film.id===nav.filmId)?nav.filmId:null);}
  window.addEventListener('popstate',onPop);return()=>{controller.abort();pendingRef.current?.controller.abort();window.removeEventListener('popstate',onPop);};
 },[cancel,update]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(session));}catch{setStorageWarning(true);}},[session,ready]);
 function goResults(){if(current.current.cursor<0)return;setError('');setView('results');history.pushState({closeup:true,view:'results'} satisfies Nav,'','#trail');window.scrollTo(0,scrollBySnapshot.current[active?.id]??0);}
 function home(){cancel();setError('');if(active)scrollBySnapshot.current[active.id]=window.scrollY;setDrawerId(null);setView('entry');if(history.state?.view==='results')history.back();else history.replaceState({closeup:true,view:'entry'} satisfies Nav,'',location.pathname);window.scrollTo(0,0);}
 function openFilm(id:string){const sn=current.current.snapshots[current.current.cursor];if(!sn?.recommendations.some(r=>r.film.id===id))throw new Error('This film is not in the current recommendations.');if(pendingRef.current)return;setError('');lastPoster.current=document.activeElement as HTMLElement;setDrawerId(id);const state={closeup:true,view:'results',filmId:id} satisfies Nav;if(history.state?.filmId)history.replaceState(state,'',`#film/${encodeURIComponent(id)}`);else history.pushState(state,'',`#film/${encodeURIComponent(id)}`);}
 function closeDrawer(){cancel();setDrawerId(null);if(history.state?.filmId)history.back();else lastPoster.current?.focus();}
 function restore(cursor:number){if(pendingRef.current)return;const s=current.current;if(s.snapshots[s.cursor])scrollBySnapshot.current[s.snapshots[s.cursor].id]=window.scrollY;update(restoreSnapshot(s,cursor));setHistoryOpen(false);setError('');history.replaceState({closeup:true,view:'results'} satisfies Nav,'','#trail');requestAnimationFrame(()=>{window.scrollTo(0,scrollBySnapshot.current[s.snapshots[cursor].id]??0);heading.current?.focus({preventScroll:true});});}
 async function generate(follow?:Film){
  if(pendingRef.current)return;const state=current.current;const base=state.snapshots[state.cursor];const seeds=follow?base.seeds:state.seedDraft;const trail=follow?[...base.trail,follow]:[];if(!seeds.length)throw new Error('Choose at least one starting film.');if(trail.length>30){setError('This trail has reached 30 steps. Return to your starting films to begin a new trail.');return;}
  const id=crypto.randomUUID();const controller=new AbortController();const operation:Pending={id,controller,kind:follow?'follow':'initial',film:follow};pendingRef.current=operation;setPending(operation);setError('');
  try{const response=await fetch('/api/recommendations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:id,baseSnapshotId:base?.id??null,seeds:seeds.map(f=>f.id),trail:trail.map(f=>f.id)}),signal:AbortSignal.any([controller.signal,AbortSignal.timeout(125000)])});const data=await response.json() as ApiBatch;if(!response.ok)throw new Error(data.error?.message||'Could not finish this search. Please try again.');if(pendingRef.current?.id!==id||controller.signal.aborted)return;
   if(data.requestId!==id||data.baseSnapshotId!==(base?.id??null))throw new Error('The response belongs to an older trail. Please try again.');
   if(!data.recommendations.length)throw new Error(data.mode==='collection'&&seeds.length+trail.length>=collection.length?'You have reached the end of this collection. Close this panel, then use Undo or start a new trail.':follow?'No more supported connections from this step. Close this panel and try another film.':'No supported connections found. Try a different starting film.');
   const snapshot=SnapshotSchema.parse({id:crypto.randomUUID(),createdAt:data.generatedAt,seeds:data.seeds,trail:data.trail,recommendations:data.recommendations,sources:data.sources,mode:data.mode});
   const next=commitSnapshot(current.current,snapshot,!follow);update(next);pendingRef.current=null;setPending(null);setView('results');setDrawerId(null);
   if(follow){if(history.state?.filmId)history.back();else history.replaceState({closeup:true,view:'results'} satisfies Nav,'','#trail');toast(`${follow.title} added to your trail.`);}else history.pushState({closeup:true,view:'results'} satisfies Nav,'','#trail');
   requestAnimationFrame(()=>{window.scrollTo(0,0);heading.current?.focus({preventScroll:true});});return snapshot;
  }catch(e){if(pendingRef.current?.id===id&&!controller.signal.aborted)setError(e instanceof Error&&e.name!=='ZodError'?e.message:'The results could not be verified. Your trail is unchanged.');}
  finally{if(pendingRef.current?.id===id){pendingRef.current=null;setPending(null);}}
 }
 function addSeed(film:Film){if(pendingRef.current)return;const s=current.current;if(s.seedDraft.some(f=>f.id===film.id)){toast(`${film.title} is already selected.`);return;}if(s.seedDraft.length>=8)return;update({...s,seedDraft:[...s.seedDraft,film]});setError('');}

 // WebMCP uses the exact same validated actions as the visible interface.
 const actions=useRef({read:()=>({}),stage:(_ids:string[])=>{},discover:async()=>({}),inspect:(_id:string)=>{},follow:async(_id:string)=>({}),undo:()=>{}});
 actions.current={read:()=>{const s=current.current;const sn=s.snapshots[s.cursor];return {view,mode,seeds:(view==='results'&&sn?sn.seeds:s.seedDraft).map(f=>({id:f.id,title:f.title})),trail:sn?.trail.map(f=>({id:f.id,title:f.title}))??[],step:s.cursor,recommendations:sn?.recommendations.map(r=>({id:r.film.id,title:r.film.title,year:r.film.year}))??[]};},stage:ids=>{if(view!=='entry'||pendingRef.current)throw new Error('Return to starting films before staging seeds.');if(!Array.isArray(ids)||ids.length<1||ids.length>8||new Set(ids).size!==ids.length)throw new Error('Provide 1–8 unique film IDs.');const selected=ids.map(id=>collection.find(f=>f.id===id));if(selected.some(f=>!f))throw new Error('Unknown collection film.');update({...current.current,seedDraft:selected as Film[]});},discover:async()=>{if(view!=='entry'||pendingRef.current||!current.current.seedDraft.length)throw new Error('Choose starting films in the entry screen first.');const result=await generate();if(!result)throw new Error('Discovery was not committed.');return {step:0,recommendations:result.recommendations.length};},inspect:openFilm,follow:async id=>{const sn=current.current.snapshots[current.current.cursor];const r=sn?.recommendations.find(r=>r.film.id===id);if(!r||pendingRef.current)throw new Error('Choose a current recommendation when research is idle.');const result=await generate(r.film);if(!result)throw new Error('Follow was not committed; the previous trail is unchanged.');return {step:result.trail.length,film:id,recommendations:result.recommendations.length};},undo:()=>{if(current.current.cursor<=0||pendingRef.current)throw new Error('There is no follow to undo.');restore(current.current.cursor-1);}};
 useEffect(()=>{type Tool={name:string,title:string,description:string,inputSchema:object,annotations:{readOnlyHint:boolean},execute:(input:any)=>unknown};const ctx=(document as Document&{modelContext?:{registerTool:(t:Tool,o:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();const empty={type:'object',properties:{},additionalProperties:false};const idSchema={type:'object',properties:{filmId:{type:'string'}},required:['filmId'],additionalProperties:false};const list:Tool[]=[{name:'closeup_read_trail',title:'Read current film trail',description:'Read visible seeds, trail and recommendations.',inputSchema:empty,annotations:{readOnlyHint:true},execute:()=>actions.current.read()},{name:'closeup_stage_seeds',title:'Choose starting films',description:'Stage 1–8 reference collection film IDs in the entry screen. Does not start research.',inputSchema:{type:'object',properties:{filmIds:{type:'array',items:{type:'string'},minItems:1,maxItems:8}},required:['filmIds'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{actions.current.stage(input?.filmIds);await new Promise(r=>requestAnimationFrame(r));return actions.current.read();}},{name:'closeup_discover_films',title:'Discover from starting films',description:'Generate sourced recommendations from staged seeds and start a new trail only after success.',inputSchema:empty,annotations:{readOnlyHint:false},execute:()=>actions.current.discover()},{name:'closeup_inspect_film',title:'Read why this film',description:'Open the evidence drawer for one current recommendation without following it.',inputSchema:idSchema,annotations:{readOnlyHint:false},execute:async input=>{if(typeof input?.filmId!=='string')throw new Error('filmId is required.');actions.current.inspect(input.filmId);await new Promise(r=>requestAnimationFrame(r));return {opened:input.filmId};}},{name:'closeup_follow_film',title:'Follow a film',description:'Add a current recommendation to the trail and research its next connections. Commits only on success.',inputSchema:idSchema,annotations:{readOnlyHint:false},execute:input=>{if(typeof input?.filmId!=='string')throw new Error('filmId is required.');return actions.current.follow(input.filmId);}},{name:'closeup_undo_follow',title:'Undo last follow',description:'Restore the previous saved recommendation batch without new research.',inputSchema:empty,annotations:{readOnlyHint:false},execute:async()=>{actions.current.undo();await new Promise(r=>requestAnimationFrame(r));return actions.current.read();}}];for(const tool of list)try{void Promise.resolve(ctx.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort();},[]);

 const previous=session.snapshots[session.cursor-1];const isNew=(id:string)=>!!previous&&!previous.recommendations.some(r=>r.film.id===id);const activeMode=active?.mode??mode;
 return <main className={view==='results'&&active?'result-page':'entry-page'} aria-busy={!ready}>
  <Toaster position="bottom-center" toastOptions={{className:'closeup-toast'}}/>
  {view==='entry'||!active?<><div className="entry-brand"><Brand/></div><section className="entry-surface" aria-label="Starting films">
   <FilmSearch seeds={session.seedDraft} onAdd={addSeed} disabled={!!pending||session.seedDraft.length>=8} mode={mode}/>
   <p className="input-hint">{session.seedDraft.length===8?'8 starting films selected. Remove one to add another.':mode==='collection'?'Search 16 films by title, director, or Korean title.':'Start with a film that stays with you.'}</p>
   {session.seedDraft.length>0&&<><div className="seed-posters">{session.seedDraft.map(f=><div className="seed-film" key={f.id}><FilmPoster film={f}/><button className="seed-remove" aria-label={`Remove ${f.title}`} disabled={!!pending} onClick={()=>{update({...current.current,seedDraft:current.current.seedDraft.filter(s=>s.id!==f.id)});setError('');}}><X size={14}/></button><strong>{f.title}</strong><small>{f.year}</small></div>)}</div><button className="primary discover" disabled={!!pending} onClick={()=>void generate()}>{pending?<><LoaderCircle className="spinning" size={18}/>{mode==='live'?'Finding connections…':'Following the connections…'}</>:<>{active?'Start new trail':'Discover films'}<ArrowRight size={18}/></>}</button>{pending?<button className="text-button entry-cancel" onClick={cancel}>Cancel</button>:<p className="seed-hint">{session.seedDraft.length} starting film{session.seedDraft.length>1?'s':''} · equal influence</p>}</>}
   {error&&<div className="inline-error entry-error" role="alert"><p>{error}</p><button onClick={()=>void generate()} disabled={!!pending}>Try again</button></div>}
   {active&&!pending&&<button className="resume text-button" onClick={goResults}>Resume your trail <ArrowRight size={15}/></button>}
   {pending?.kind==='initial'&&<div className="initial-progress" role="status"><span>Finding connections in {mode==='live'?'criticism, scholarship and programmes':'the reference collection'}.</span>{mode==='live'&&<small>Good sources take a little time. You can cancel whenever you like.</small>}<div className="mini-skeletons">{[0,1,2,3,4,5].map(i=><Skeleton key={i} className="mini-skeleton"/>)}</div></div>}
  </section></>:<>
   <header className="result-header"><Brand small onClick={home}/><div className="trail-area"><span className="eyebrow">YOUR TRAIL</span><div className="trail-line"><Popover><PopoverTrigger asChild><button className="seed-bundle" aria-label="View starting films"><span className="seed-stack">{active.seeds.slice(0,3).map(f=><span key={f.id}><FilmPoster film={f} decorative/></span>)}</span><span>Seeds · {active.seeds.length}</span></button></PopoverTrigger><PopoverContent align="end" className="seed-popover"><h2>Starting films</h2>{active.seeds.map(f=><div className="small-film-row" key={f.id}><FilmPoster film={f}/><span><strong>{f.title}</strong><small>{f.year} · {f.director}</small></span></div>)}</PopoverContent></Popover>
    <div className="trail-followed">{active.trail.map((f,i)=><div className={`trail-item ${i===active.trail.length-1?'latest':''}`} key={f.id}><ChevronRight size={14}/><button title={`${i+1} · ${f.title}`} aria-label={`Restore step ${i+1}: ${f.title}`} disabled={!!pending} onClick={()=>restore(i+1)}><FilmPoster film={f} decorative/><span>{i===active.trail.length-1&&<><strong>{f.title}</strong><small>Latest</small></>}</span></button></div>)}</div></div>
    <div className="trail-controls"><button className="text-button" onClick={()=>restore(session.cursor-1)} disabled={session.cursor<=0||!!pending}><Undo2 size={14}/>Undo last follow</button><Popover open={historyOpen} onOpenChange={setHistoryOpen}><PopoverTrigger asChild><button className="text-button" disabled={!!pending}><History size={14}/>History</button></PopoverTrigger><PopoverContent align="end" className="history-popover"><h2>Trail history</h2><p>Restore films and sources exactly as they were.</p><div className="history-list">{session.snapshots.map((sn,i)=><button key={sn.id} onClick={()=>restore(i)} className={i===session.cursor?'current':''}><span className="step-number">{String(i).padStart(2,'0')}</span>{i>0?<FilmPoster film={sn.trail[sn.trail.length-1]} decorative/>:<BookOpen size={23}/>}<span><strong>{i===0?'Starting films':sn.trail[sn.trail.length-1].title}</strong><small>{i===0?sn.seeds.map(f=>f.title).join(' + '):`${sn.recommendations.length} connections`}</small></span>{i===session.cursor&&<Check size={16}/>}</button>)}</div></PopoverContent></Popover></div>
   </div></header>
   <section className="results-content" aria-label="Recommended films"><div className="results-heading"><div><h1 tabIndex={-1} ref={heading}>{active.trail.length?`Following ${active.trail[active.trail.length-1].title}`:'From your starting films'}</h1><p>{active.trail.length?'The latest film leads. Your earlier choices stay in the picture.':'A connection is a place to begin. Open a poster to read why.'}</p></div><span className="result-count">{active.recommendations.length} film{active.recommendations.length!==1?'s':''}</span></div>
    <div className="poster-grid">{active.recommendations.map(r=><button key={r.film.id} className="film-card" onClick={()=>openFilm(r.film.id)} aria-label={`Why ${r.film.title}, ${r.film.year}?`}><div className="poster-wrap"><FilmPoster film={r.film}/>{isNew(r.film.id)&&<span className="new-label">NEW TO THIS STEP</span>}<span className="poster-action">Why this film<ArrowUpRight size={19}/></span></div><strong>{r.film.title}</strong><small>{r.film.year}<span> · </span>{r.film.director}</small></button>)}</div>
    <div className="results-note"><span>Only connections with sources. No ratings, no popularity scores.</span>{activeMode==='collection'&&<button className="text-button" onClick={()=>setCredits(true)}>About this collection<ArrowUpRight size={13}/></button>}</div>
   </section>
  </>}

  <Sheet open={!!detail} onOpenChange={open=>{if(!open)closeDrawer();}}><SheetContent className="film-drawer" showCloseButton={false} onCloseAutoFocus={e=>{e.preventDefault();if(pendingRef.current)return;lastPoster.current?.focus({preventScroll:true});}}>
   {detail&&<><div className="drawer-top"><span className="eyebrow">A CLOSER LOOK</span><button className="icon-button" aria-label="Close film details" onClick={closeDrawer}><X size={21}/></button></div><div className="drawer-scroll"><div className="detail-identity"><div className="detail-poster"><FilmPoster film={detail.film}/></div><div><SheetTitle className="film-title">{detail.film.title}</SheetTitle><SheetDescription className="film-meta">{detail.film.director} · {detail.film.year}</SheetDescription><p className="film-country">{detail.film.country}{detail.film.runtime?` · ${detail.film.runtime} min`:''}</p></div></div>
    <section className="why-section"><h2>Why this film</h2><div className="connection-anchor"><span>From {detail.connections[0].anchorTitle}</span><ArrowRight size={14}/><span>{detail.film.title}</span></div><p className="why-text">{detail.connections[0].why}</p><span className={`relation-label ${detail.connections[0].relation}`}><span/>{relationLabel[detail.connections[0].relation]}</span>
     {detail.connections.length>1&&<Accordion type="single" collapsible className="other-connections"><AccordionItem value="more"><AccordionTrigger>Also connected to {detail.connections.slice(1).map(c=>c.anchorTitle).join(', ')}</AccordionTrigger><AccordionContent>{detail.connections.slice(1).map(c=><div key={c.anchorId}><strong>{c.anchorTitle}</strong><p>{c.why}</p><small>{relationLabel[c.relation]}</small></div>)}</AccordionContent></AccordionItem></Accordion>}
    </section>
    <section className="evidence-section"><div className="evidence-heading"><h2>Read the sources</h2><span>{detail.sourceIds.length}</span></div>{detail.sourceIds.map(id=>active.sources.find(s=>s.id===id)).filter((s):s is Source=>!!s).map((s,i)=><article className="evidence-card" key={s.id}><div className="evidence-kicker"><span>{String(i+1).padStart(2,'0')}</span><span>{sourceLabel[s.type]}</span>{s.accessLevel==='abstract'&&<em>Abstract</em>}</div><a href={safeLink(s.url)} target="_blank" rel="noopener noreferrer" className="source-title">{s.title}<ArrowUpRight size={17}/></a><p className="source-byline">{[s.author,s.publisher,readableDate(s.date)].filter(Boolean).join(' · ')}</p><p className="source-summary">{s.summary}</p>{s.scope==='programme_context'&&<small className="context-note">Programme context, not proof of similarity.</small>}</article>)}</section>
    <p className="evidence-footnote">Connections can be a critic’s comparison or our reading of the sources. They are not claims of influence unless the text says so.</p>
   </div><div className="drawer-action">{session.cursor<session.snapshots.length-1&&<p className="replace-note">Following here will replace the later steps in your trail.</p>}{error&&<p className="inline-error" role="alert">{error}</p>}{pending?.kind==='follow'&&<p className="pending-note" role="status">Checking the next connections. Your current trail is kept.</p>}<div className="follow-buttons"><button className="primary follow" disabled={!!pending} onClick={()=>void generate(detail.film)}>{pending?<><LoaderCircle className="spinning" size={18}/>Following…</>:<>Follow this film<ArrowRight size={18}/></>}</button>{pending&&<button className="secondary" onClick={cancel}>Cancel</button>}</div></div></>}
  </SheetContent></Sheet>

  <Dialog open={credits} onOpenChange={setCredits}><DialogContent className="credits-dialog"><DialogTitle className="credits-title">A small collection. Real connections.</DialogTitle><DialogDescription className="credits-description">{mode==='collection'?'You are exploring 16 films through 32 hand-checked connections. This is a reference collection, not live AI research.':'Live research finds connections in criticism, scholarship and festival writing, then checks its sources.'}</DialogDescription><p>Your trail stays in this browser. There are no CLOSEUP accounts and no cloud history.</p><p>Academic writing, professional criticism and official programmes provide the evidence. Catalogue associations are labeled as curation. Interpretations are identified as CLOSEUP readings.</p>{mode==='collection'&&<p className="connection-setup">Search covers this collection only. Each step follows a documented comparison or a clearly labeled reading of the sources.</p>}<div className="credits-divider"/><h3>Images & metadata</h3><p>Reference posters identify the films and remain the property of their rights holders. Live metadata and images are provided by TMDB.</p><div className="tmdb-credit"><a href="https://www.themoviedb.org" target="_blank" rel="noopener noreferrer" aria-label="The Movie Database"><img src="/tmdb-logo.svg" alt="TMDB"/></a><span>This product uses the TMDB API but is not endorsed or certified by TMDB.</span></div><a href="https://developer.themoviedb.org/docs/faq" target="_blank" rel="noopener noreferrer">TMDB attribution<ArrowUpRight size={14}/></a></DialogContent></Dialog>
  <footer className="app-footer"><button onClick={()=>setCredits(true)}>{mode==='collection'?'REFERENCE COLLECTION · 16 FILMS':'SOURCE-GROUNDED DISCOVERY'}</button>{storageWarning?<span className="storage-warning">This trail cannot be saved in this browser.</span>:<span className="storage-copy">Your trail, saved in this browser.</span>}<button onClick={()=>setCredits(true)}>Credits & sources</button></footer>
 </main>
}
