"use client";
import {useEffect,useState,useRef} from 'react';
import {Search,LoaderCircle} from 'lucide-react';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import {searchCollection} from '@/lib/catalogue';
import {titleOf,type Film,type Language} from '@/lib/domain';
import {translate,apiMessage} from '@/lib/i18n';
import {FilmPoster} from './film-poster';
export function FilmSearch({seeds,onAdd,disabled,language}:{seeds:Film[],onAdd:(film:Film)=>void,disabled:boolean,language:Language}){
 const tr=(en:string,ko:string)=>translate(language,en,ko);const [query,setQuery]=useState('');const [items,setItems]=useState<Film[]>(searchCollection(''));const [loading,setLoading]=useState(false);const [selecting,setSelecting]=useState(false);const [error,setError]=useState('');const [open,setOpen]=useState(false);const [retry,setRetry]=useState(0);const input=useRef<HTMLInputElement>(null);const selectedRequest=useRef(0);
 useEffect(()=>{const controller=new AbortController();setError('');setItems(searchCollection(query));if(query.trim().length<2){setLoading(false);return()=>controller.abort();}setLoading(true);const timer=setTimeout(async()=>{try{const response=await fetch(`/api/films/search?q=${encodeURIComponent(query.trim())}&language=${language}`,{signal:controller.signal});const data=await response.json() as {error?:{code:string,message:string},films:Film[]};if(!response.ok)throw new Error(apiMessage(data.error?.code,language,data.error?.message));if(!controller.signal.aborted)setItems(data.films);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:tr('Search is unavailable.','검색에 연결할 수 없습니다.'));}finally{if(!controller.signal.aborted)setLoading(false);}},500);return()=>{clearTimeout(timer);controller.abort();};},[query,language,retry]);
 async function select(f:Film|null){if(!f||disabled||selecting||seeds.some(s=>s.id===f.id))return;const request=++selectedRequest.current;setSelecting(true);try{let film=f;if(f.id.startsWith('tmdb:')){const r=await fetch(`/api/films/${encodeURIComponent(f.id)}?language=${language}&details=0`);const data=await r.json() as {film:Film,error?:{code:string,message:string}};if(!r.ok)throw new Error(apiMessage(data.error?.code,language,data.error?.message));film=data.film;}if(request!==selectedRequest.current)return;onAdd(film);setQuery('');setOpen(false);}catch(e){setError(e instanceof Error?e.message:tr('Could not add this film.','영화를 추가하지 못했습니다.'));}finally{if(request===selectedRequest.current){setSelecting(false);requestAnimationFrame(()=>input.current?.focus());}}}
 return <div className="film-search"><Combobox items={items} filter={null} value={null} inputValue={query} onInputValueChange={setQuery} onValueChange={select} itemToStringLabel={(f:Film)=>titleOf(f,language)} open={open&&!disabled} onOpenChange={setOpen}>
  {loading||selecting?<LoaderCircle className="search-icon spinning" size={20}/>:<Search className="search-icon" size={20}/>}<ComboboxInput ref={input} className="film-search-input" placeholder={disabled?tr('Remove a film to add another','다른 영화를 넣으려면 하나를 빼주세요'):tr('Search for a film…','어떤 영화에서 출발할까요?')} aria-label={tr('Search for a film','영화 검색')} showTrigger={false} disabled={disabled||selecting} maxLength={100}/>
  <ComboboxContent className="film-search-results" aria-label={tr('Film suggestions','영화 검색 결과')}><div className="suggestion-heading">{query?tr('MATCHING FILMS','검색 결과'):tr('STARTING POINTS','시작해 볼 영화')}{loading&&<span>{tr('Searching the database…','영화 DB 검색 중…')}</span>}</div>
  {error&&<div className="search-feedback" role="alert">{error}<button onClick={()=>setRetry(n=>n+1)}>{tr('Try again','다시 시도')}</button></div>}
  <ComboboxEmpty>{loading?tr('Finding films…','영화를 찾고 있습니다…'):tr('No films found. Try another title or original title.','검색 결과가 없습니다. 다른 제목이나 원제로 찾아보세요.')}</ComboboxEmpty><ComboboxList>{(f:Film)=><ComboboxItem key={f.id} value={f} disabled={seeds.some(s=>s.id===f.id)} className="search-option"><FilmPoster film={{...f,title:titleOf(f,language)}}/><span><strong>{titleOf(f,language)}</strong><small>{f.year}{f.director&&` · ${f.director}`}</small></span>{seeds.some(s=>s.id===f.id)&&<em>{tr('Added','추가됨')}</em>}</ComboboxItem>}</ComboboxList>
  <div className="search-keys"><span><kbd>↑</kbd><kbd>↓</kbd>{tr('move','이동')}</span><span><kbd>↵</kbd>{tr('add film','추가')}</span><span><kbd>esc</kbd>{tr('close','닫기')}</span></div></ComboboxContent>
 </Combobox></div>
}
